apiVersion: v1
kind: Service
metadata:
  name: app-8675309 #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: app-8675309
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.93
  loadBalancerIP: 192.168.0.93
  ports:
    - port: 80 #Service port
      targetPort: 8093
      protocol: TCP #The port for the container